name: Generate Snake Animation

on:
  schedule: # Запускается раз в день
    - cron: "0 0 * * *"
  workflow_dispatch: # Возможность вручную запускать workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Проверяет ваш репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Генерация SVG-анимации змейки
      - name: Generate Snake animation
        uses: Platane/snk@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/github-contribution-grid-snake.svg

      # Публикация результата в ветку output
      - name: Push generated Snake
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
          token: ${{ secrets.GITHUB_TOKEN }}

